### ISSUE TITLE
kobuki specific gazebo plugin

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki_desktop#1]
Currently its a copy of create.

Remove the dependency for the create from manifest and stack.xml's once done.

**Comment by bit-pirate** [comment]
Commit 7676a39d83e9e1156be0ca6e3b6d86f2957946d8 is nearly a complete rewrite of the plugin. It removes the dependencies to the create package and updates to the new Gazebo version (currently 1.3).

**Comment by bit-pirate** [comment]
Kobuki has now a standalone (create-independent) Gazebo plugin. Follow up on #8 for current development in Kobuki Gazebo simulation.
