### ISSUE TITLE
rosdistro is missing source info

### ISSUE THREAD

**Issue by NikolausDemmel** [yujinrobot/kobuki_desktop#29]
It seems that https://github.com/ros/rosdistro/blob/master/hydro/distribution.yaml is missing the `source` entry for `kobuki_desktop` and also others, like `kobuki_core` or `kobuki_soft`. I did not check the other ROS distros.

**Comment by jihoonl** [comment]
Just curious, what is source entry for? Does it do any specific job in the release process?

**Comment by NikolausDemmel** [comment]
Not sure about other uses, but for me it is useful in conjunction with `rosinstall_generator`. E.g.

```
$ rosinstall_generator --rosdistro hydro --repos kobuki --upstream
- git:
    local-name: kobuki
    uri: https://github.com/yujinrobot/kobuki.git
    version: 0.5.6
```

but `rosinstall_generator --rosdistro hydro --repos kobuki_desktop --upstream` errors out because of the missing entires in `rosdistro`.

**Comment by stonier** [comment]
That's one. Another is that it makes available the option to do pre-releases with the latest source instead of the latest release tarball.

**Comment by jihoonl** [comment]
Fixed.

**Comment by NikolausDemmel** [comment]
Thanks!
