### ISSUE TITLE
Kobuki dashboard

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki_desktop#4]
Bugs & ideas for Kobuki's dashboard

**Comment by bit-pirate** [comment]
Two minor bugs:
- The dashboard is not recognising, if Kobuki's battery is charged or not. Don't know, if this is a Kobuki or dashboard problem
- Add image for orange LEDs

**Comment by bit-pirate** [comment]
The missing orange background problem will be fixed, when rqt_robot_dashboard version 0.2.8 get's into public. This should happen soon, since it's already in shadow fixed. That release also contains cooler LED images. Yay!

**Comment by stonier** [comment]
Fixes needed.
- Enable motors button has no tooltip
- Enable motors doesn't disable
- Enable motors is missing an icon in disabled mode?
- Test the navigation panel with a robot, does it actually work?

**Comment by bit-pirate** [comment]
I posted an issue regarding the nav view bug:
https://github.com/ros-visualization/rqt_robot_plugins/issues/5

Let's keep an eye on it. Once it is working better, we can integrate it again. It looks like a nice addition.

**Comment by bit-pirate** [comment]
One future improvement would be setting the LED states in the dashboard by checking their actual state and not the internally created. This is done for the motors already, but is currently not possible for the LEDs, since the information is missing.

See this issue for details: https://github.com/yujinrobot/kobuki/issues/222

**Comment by ablasdel** [comment]
https://github.com/ros-visualization/rqt_robot_plugins/issues/5
The functionality I put in for the PR2 dashboard widgets didn't work its way into the rest of the dash widgets.

**Comment by stonier** [comment]
Following up in #12.
