### ISSUE TITLE
Button pressed indication - Kobuki Dashboard

### ISSUE THREAD

**Issue by jihoonl** [yujinrobot/kobuki_desktop#5]
Maybe good to implement in the future.

**Comment by bit-pirate** [comment]
Not sure if this is useful. What could the user do with this information inside the dashboard? There is already a sound feedback, when pressing a button.
But I have no objection about adding this, if others find this useful.

**Comment by stonier** [comment]
Closing. If someone really has an itch for this, scratch it (implement it!) and pull request.
