### ISSUE TITLE
/bin/sh: 1: pyrcc5: not found

### ISSUE THREAD

**Issue by wangzhaodong123** [yujinrobot/kobuki_desktop#51]
When i catkin_make my workspace,the error happened in the end:
/bin/sh: 1: pyrcc5: not found
make[2]: *** [kobuki_desktop/kobuki_qtestsuite/CMakeFiles/kobuki_qtestsuite] 错误 127
make[1]: *** [kobuki_desktop/kobuki_qtestsuite/CMakeFiles/kobuki_qtestsuite.dir/all] 错误 2
make: *** [all] 错误 2
Invoking "make -j1 -l1" failed
Can you help me solve it?Thank you.

**Comment by stonier** [comment]
Thanks! Should be fixed in #52. Releasing in 0.5.7.

Reopen if you still have problems.
