### ISSUE TITLE
Pyrcc5: not found

### ISSUE THREAD

**Issue by wangzhaodong123** [yujinrobot/kobuki_desktop#53]
I met a problem when i make my space. It stopped here:
[ 98%] Built target kobuki_nodelet
/bin/sh: 1: pyrcc5: not found
make[2]: *** [kobuki_desktop/kobuki_qtestsuite/CMakeFiles/kobuki_qtestsuite] 错误 127
make[1]: *** [kobuki_desktop/kobuki_qtestsuite/CMakeFiles/kobuki_qtestsuite.dir/all] 错误 2
make: *** [all] 错误 2
Invoking "make -j1 -l1" failed
Can you tell me the reason and help me solve it? Thank you.

**Comment by stonier** [comment]
You already raised this issue in #51?

**Comment by RobotQZ** [comment]
I have met the same problem now,anyone can help me? please

**Comment by Abdul-Mukit** [comment]
`sudo apt-get install pyqt5-dev-tools`
worked for me.

**Comment by stonier** [comment]
What distro are you on?

**Comment by stonier** [comment]
If you have version >= 0.5.7 rosdep should nab it for you. Making this a duplicate of #51.
