### ISSUE TITLE
Dashboard battery update time

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki_desktop#7]
Currently it's buggy - set to the battery percantage!

But is this even used by the graphical display?

**Comment by bit-pirate** [comment]
This may already be solved. The current indicator show the current charge with a precise percentage.

**Comment by stonier** [comment]
It's the update_time value, not the percentage.

https://github.com/yujinrobot/kobuki_desktop/blob/hydro-devel/kobuki_dashboard/src/kobuki_dashboard/dashboard.py#L47

**Comment by stonier** [comment]
This shows up as a tooltip in the dashboard.

https://github.com/ros-visualization/rqt_robot_plugins/blob/hydro-devel/rqt_robot_dashboard/src/rqt_robot_dashboard/battery_dash_widget.py#L79

**Comment by stonier** [comment]
rqt_robot_dashboard's update_time is badly named. It actually just shows % remaining, not time. Just does it in text over a tooltip rather than a graphical battery icon.

Not a big drama - calculating time left in hrs/mins is not reliable anyway given that its such a variable nonlinear function and we have little idea which battery is inside (4S1P or 4S2P). So happy with the % tooltip, lets close this.

Ideally should change the name of the function upstream, but not a big issue for us to worry about.
